name: deploy

on:
  workflow_dispatch:

jobs:

  pypi:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Package
        env:
          PIP_INDEX_URL: https://:2023-04-16T23:56:46.279633Z@time-machines-pypi.sealsecurity.io/
        run: |
          pip install --upgrade build
          echo "hatchling==1.14.0" > "${RUNNER_TEMP}/build-constraints.txt"
          PIP_CONSTRAINT="${RUNNER_TEMP}/build-constraints.txt" python -m build -s -w
      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: pypi-dist
          path: dist/*
          if-no-files-found: error
